## Enable HTTPS with SSL keystore
server.port=8443
server.ssl.key-alias=artemis-ssl
# Ensure this matches the password you set during keytool generation
server.ssl.key-store-password=JohnWick
server.ssl.key-store=classpath:artemis-keystore.p12
server.ssl.key-store-type=PKCS12